//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestYourLearning.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDBEntities : DbContext
    {
        public TestDBEntities()
            : base("name=TestDBEntities")
        {
        }
        private static TestDBEntities _context;
        public static TestDBEntities GetContext()
        {
            if (_context == null)
                _context = new TestDBEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<AnswerInQuestion> AnswerInQuestion { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GroupIndex> GroupIndex { get; set; }
        public virtual DbSet<GroupName> GroupName { get; set; }
        public virtual DbSet<Human> Human { get; set; }
        public virtual DbSet<ImageProfile> ImageProfile { get; set; }
        public virtual DbSet<Lecture> Lecture { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<QuestionInTest> QuestionInTest { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TestScore> TestScore { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
